sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t  arun-ramesh07/docker-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true arun-ramesh07/docker-react npm run test -- --coverage 
